<?php return; ?>
<div id="myCarousel" class="carousel slide">
    <!-- Indicators -->
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner">
        <div class="item active">
            <div class="fill" style="background:#ccc;"></div>
            <div class="carousel-caption">
                <iframe title="YouTube video player" class="youtube-player" type="text/html" width="425" height="349" src="http://www.youtube.com/embed/xRGSzmp2dAk?rel=0" frameborder="0" allowFullScreen></iframe>
            </div>
        </div>
        <div class="item">
            <div class="fill" style="background:#ccc;"></div>
            <div class="carousel-caption">
                <img src="/photos/searches.jpg" />
            </div>
        </div>
        <div class="item">
            <div class="fill" style="background:#ccc;"></div>
            <div class="carousel-caption">
                <h1>Additional Layout Options at <a href="http://startbootstrap.com">http://startbootstrap.com</a></h1>
            </div>
        </div>
    </div>

    <!-- Controls -->
    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
        <span class="icon-prev"></span>
    </a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next">
        <span class="icon-next"></span>
    </a>
</div>
