Year/Make/Model/Trim Database (Up to 2013) - $100
<form name="PrePage" method = "post" action = "https://Simplecheckout.authorize.net/payment/CatalogPayment.aspx"> <input type = "hidden" name = "LinkId" value ="e42f131b-9118-4327-8952-962930d6c1a6" /> <input type = "submit" value = "Buy Now!" /> </form> 
<hr />
<table border="1" cellpadding="10" align="center">
	<tr>
		<td></td>
		<td>Lite</td>
		<td>Starter</td>
		<td>Full</td>
		<td>Plus</td>
	</tr>
    <tr>
        <td><a href="about/search.php">Search By Vehicle</a></td>
        <td><img src="/images/check.png" /></td>
        <td><img src="/images/check.png" /></td>
        <td><img src="/images/check.png" /></td>
        <td><img src="/images/check.png" /></td>
    </tr>
    
    <tr>
        <td><a href="about/search.php">Universal Products</a></td>
        <td><img src="/images/check.png" /></td>
        <td><img src="/images/check.png" /></td>
        <td><img src="/images/check.png" /></td>
        <td><img src="/images/check.png" /></td>
    </tr>
    
    <tr>
        <td><a href="about/faceted.php">Faceted (Layered) Navigation</a></td>
        <td><img src="/images/check.png" /></td>
        <td><img src="/images/check.png" /></td>
        <td><img src="/images/check.png" /></td>
        <td><img src="/images/check.png" /></td>
    </tr>
    
    <tr>
        <td><a href="about/admin.php">Administration Panel</a></td>
        <td><img src="/images/check.png" /></td>
        <td><img src="/images/check.png" /></td>
        <td><img src="/images/check.png" /></td>
        <td><img src="/images/check.png" /></td>
    </tr>
    
	<tr>
		<td><a href="about/checkout.php">Automotive Checkout</a></td>
		<td><img src="/images/check.png" /></td>
		<td><img src="/images/check.png" /></td>
		<td><img src="/images/check.png" /></td>
		<td><img src="/images/check.png" /></td>
	</tr>
	
	<tr>
		<td><a href="about/data.php">Year/Make/Model/Trim Database</a></td>
		<td></td>
		<td><img src="/images/check.png" /></td>
		<td><img src="/images/check.png" /></td>
		<td><img src="/images/check.png" /></td>
	</tr>
	
	<tr>
		<td><a href="about/data.php">Import/Export</a></td>
		<td></td>
		<td><img src="/images/check.png" /></td>
		<td><img src="/images/check.png" /></td>
		<td><img src="/images/check.png" /></td>
	</tr>
	<tr>
		<td>
			<a href="/modules/logos.php">Logos Module</a>
		</td>
		<td></td>
		<td><img src="/images/check.png" /></td>
		<td><img src="/images/check.png" /></td>
		<td><img src="/images/check.png" /></td>
	</tr>
    <tr>
        <td>
            <a href="/modules/logos.php">Logo Artwork</a>
        </td>
        <td></td>
        <td><img src="/images/check.png" /></td>
        <td><img src="/images/check.png" /></td>
        <td><img src="/images/check.png" /></td>
    </tr>
	<tr>
		<td>
			<a href="/modules/fitment_notes.php">Fitment Notes</a>
		</td>
		<td></td>
		<td><img src="/images/check.png" /></td>
		<td><img src="/images/check.png" /></td>
		<td><img src="/images/check.png" /></td>
	</tr>
	<tr>
		<td>
			<a href="http://vehiclefits.com/support.php">Phone &amp; E-Mail Support</a>
		</td>
		<td><img src="/images/check.png" /></td>
		<td><img src="/images/check.png" /></td>
		<td><img src="/images/check.png" /></td>
		<td><img src="/images/check.png" /></td>
	</tr>
	<tr>
		<td>Updates</td>
		<td><img src="/images/check.png" /></td>
		<td><img src="/images/check.png" /></td>
		<td><img src="/images/check.png" /></td>
		<td><img src="/images/check.png" /></td>
	</tr>
	
    <tr>
        <td>Installation & Individual Customization</td>
        <td><img src="/images/check.png" /></td>
        <td><img src="/images/check.png" /></td>
        <td><img src="/images/check.png" /></td>
        <td><img src="/images/check.png" /></td>
    </tr>
    <tr>
		<td align="center" colspan="5">Unlimited** <b>Installation</b>, Support &amp; Updates Come For 1 Year Standard!!</td>
	</tr>
	<tr>
		<td><a href="http://vehiclefits.com/about/seo.php">Automotive SEO</a></td>
		<td></td>
		<td></td>
		<td><img src="/images/check.png" /></td>
		<td><img src="/images/check.png" /></td>
	</tr>
	<tr>
		<td><a href="http://vehiclefits.com/about/bundle.php">Suspension Kit / Kit</a></td>
		<td></td>
		<td></td>
		<td><img src="/images/check.png" /></td>
		<td><img src="/images/check.png" /></td>
	</tr>
	<tr>
		<td><a href="http://vehiclefits.com/modules/wheel.php">Wheels</a></td>
		<td></td>
		<td></td>
		<td></td>
		<td><img src="/images/check.png" /></td>
	</tr>
	<tr>
		<td><a href="http://vehiclefits.com/modules/tire.php">Tires</a></td>
		<td></td>
		<td></td>
		<td></td>
		<td><img src="/images/check.png" /></td>
	</tr>
	<tr>
		<td><a href="http://vehiclefits.com/modules/wheel-adapter.php">Wheel Adapters</a></td>
		<td></td>
		<td></td>
		<td></td>
		<td><img src="/images/check.png" /></td>
	</tr>
	<tr>
		<td><a href="http://vehiclefits.com/modules/paint.php">Paint Codes</a></td>
		<td></td>
		<td></td>
		<td></td>
		<td><img src="/images/check.png" /></td>
	</tr>
	
	<tr>
		<td><a href="http://vehiclefits.com/unit_tests.php">Unit Tests & Nightly Builds</a></td>
		<td></td>
		<td></td>
		<td></td>
		<td><img src="/images/check.png" /></td>
	</tr>
	
	<tr>
		<td>
			<strong>Cost</strong>
		</td>
		<td>
                    <form name="PrePage" method = "post" action = "https://Simplecheckout.authorize.net/payment/CatalogPayment.aspx"> <input type = "hidden" name = "LinkId" value ="87576e65-23d5-405c-8e07-e013263fb1cf" /> <input type = "submit" value = "Buy" /> </form>
		    $175
		</td>
		<td>
                    <form name="PrePage" method = "post" action = "https://Simplecheckout.authorize.net/payment/CatalogPayment.aspx"> <input type = "hidden" name = "LinkId" value ="19bd83e6-f338-42f0-b8ef-8551c6a07f10" /> <input type = "submit" value = "Buy" /> </form>

            $399
		</td>
		<td>
		    <form name="PrePage" method = "post" action = "https://Simplecheckout.authorize.net/payment/CatalogPayment.aspx"> <input type = "hidden" name = "LinkId" value ="29a86d48-7728-46ed-8d27-6c30cfa3ef37" /> <input type = "submit" value = "Buy" /> </form>
		    $945
		</td>
		<td>
		    <form name="PrePage" method = "post" action = "https://Simplecheckout.authorize.net/payment/CatalogPayment.aspx"> <input type = "hidden" name = "LinkId" value ="d521bbc6-22eb-420e-83bc-914635cb6f5e" /> <input type = "submit" value = "Buy" /> </form>
		    $1,998.08
		</td>
	</tr>
</table>
<span style="font-size:smaller">** We will install, update &amp; support your software an unlimited number of times for up to 1 year. Vehiclefits retains the right to end support sooner than 1 year if we feel you are intentionally abusing unlimited support.</span>

<br />
Received a quote or bill from us?
<form name="PrePage" method = "post" action = "https://Simplecheckout.authorize.net/payment/CatalogPayment.aspx"> <input type = "hidden" name = "LinkId" value ="ac887789-ae8d-45eb-a086-33396d8c9700" /> <input type = "submit" value = "Pay Bill" /> </form>