<div class="frontend">
	<h1>Customer Benefits</h1>
	<p class="left">
		The vehicle fit extension has been implemented as an enhancement for the <a target="_blank" href="http://magentocommerce.com">Magento e-commerce platform</a>. From the customer's perspective the user picks a make, then the models load in via ajax. After subsequently choosing a model the customer can pick the year / options. The extension
		can do make model year, make model option, make model option year, or any other combination that is needed. 
	</p>
	
	<p class="right">
		You may need to filter on something else besides just make model year. The Make Model Year extension has even been used to filter sewing machine parts
		( so a user desiring to replace a part on that machine could filter down to only the products applicable to his or her specific make &amp; model of that machine ). It would be possible to use bracket size ( for matching up RV hitches ),
		engine size, or any other sort of hiercarchy / fitment / connector / adaptor / or sizing system the customer is used to searching and filtering products with.
	</p>
	
	<p class="right">
		The vehicle the user is searching for can be displayed anywhere within your site, to provide a clear reference point and provide a more personalized customer experience.
		<br />
		<img src="/images/myvehicle.jpg" alt="the personalization features of the vehicle fit extension showing the my current vehicle information" />
	</p>
	
	<p class="right">
		The vehicle fit filter integrates with Magento's layered navigation system allowing potential customers to combine criteria to further filter down the results of available product. For example the user
		could want to see all rims that fits their vehicle that are 22" and under $4,000. With the extension they could do so.
	</p>
</div>
<p>
	<h1>Administration</h1>
	 From the admin control panel a product ( for e.g. a wheel ) can have multiple "fits" assigned to them, users then choose their make model &amp; year on the front-end and the extension will find all matching parts for that fit.
	 <br />
	 <img src="/images/admin_product_edittab.jpg" alt="Adding fits to a product with the magento plugin" />
</p>

<p>
	 The last vehicle application fit the customer had searched on will be saved and displayed on the order view page, allowing the order fulfillers to verify the customer purchased a part for the correct fit.
	 This allows an additional step to catch and correct errors before they are shipped out, ultimately reducing incorrect orders.
	 <br />
	 <img src="/images/order_view_fit.jpg" />
</p>
<p>
	 If you are inputting your fit assignments by hand you may need to assign a product to many individual fits. To speed up this process you can
	  pick a top level attribute ( eg. make "honda" ) and have it add all the options ( models / options / years ) that are hondas. You could then go thru and uncheck any fits that do not apply.
</p>

<p>
	<h1>Additional Benefits</h1>
	 You can import vehicle fit mappings by creating a spreedsheet, either by hand or from existing data that you have. If you have any custom needs as far as matching the products we can set up a custom solution
	 to automatically match up products as they are added by using a spreadsheet to lookup fits ( either by some secondary attribute or code or bolt pattern that you may use ), it could be updated automatically for instance
	 from your manufacturer's data source.
	 <br />
	 <img src="/images/spreadsheet.jpg" alt="importing product to vehicle fit mappings" />
</p>

<p>
	 If you have your own database of makes models and years to use, as long as it is normalized it will only take you minutes to import the tables directly. For everyone else you can edit the available makes models and years
	 right from the admin control panel. The interface allows you to add new makes, edit &amp; delete existing makes, models, and years.
</p>

<img src="/images/admin_product_add.jpg" alt="configuring the makes models and years that users will be able to filter products by, and will be available for assigning fits to products on the product edit page" />

<p>
	The available makes models and years can be pre-populated for you from any public domain source. There is a small fee involved in performing the data scraping of course.
</p>

<p>
	 If you have your own database of makes models and years to use, as long as it is normalized it will only take you minutes to import the tables directly. For everyone else you can edit the available makes models and years
	 right from the admin control panel. The interface allows you to add new makes, edit &amp; delete existing makes, models, and years.
</p>
<img src="/images/admin_product_add.jpg" alt="configuring the makes models and years that users will be able to filter products by, and will be available for assigning fits to products on the product edit page" />
<p>
	The system can be set up to do year ranges, for instance if you want to be able to store "1991 - 2006" as an actual fit and apply all of those years to a product at once. Customers would then select the range of years that applied.
</p>
