<h3>FREE Automotive Data</h3>
<p>A FREE database of Automotive database is now offered to help kick start your vehicle mapping venture!.</p>
<a href="http://vehicle-data.com">Browse the FREE database of vehicles</a>
<br />
<a href="http://www.ne8.net/contact/5_Contact_Us.php">Contact Us to execute the free license</a>, no catches. Just link back

<h3>Paint Codes</h3>
We have paint codes data, containing:
<ol><li>the manufacturer paint code</li><li>paint color name</li><li>hexidecimal representation of the color</li></ol>

<h3>Wheel Fitment & Bolt Patterns</h3>
<p>Wheel Fitments are available for:<p>
<ol><li>Cars</li><li>Trucks</li><li>SUV's</li></ol>

<p>We have data for:</p>
<ol><li>Tire Width</li><li>OE offset</li><li>bolt pattern distance</li><li>wether it uses bolts or nuts</li><li>and finally. the hub size.</li></ol>


<h3>Other Automotive Databases</h3>
<p>We can get our hands on almost any database that you need, please call for a quote if we do not have what you need listed.</p>

