<h1>Magento Demo</h1>
<div class="magentoDemo">
    <div class="magento-frontend">
        <h2>Front-end</h2>
        <a href="http://demo.vehiclefits.com/index.php">Demo Front-End</a>
    </div>

    <div class="magento-backend">
        <h2>Admin Panel</h2>
        <a href="http://demo.vehiclefits.com/index.php/admin">Demo the Admin</a><br /> Username: admin<br /> Password: admin123
    </div>
    <i>Demo is reset hourly</i>
</div>

<h1>Zend Framework 1 Demo</h1>
<div class="magentoDemo">
    <div class="magento-frontend">
        <h2>Front-end</h2>
        <a href="http://zendframework1demo.vehiclefits.com/index.php">Demo Front-End</a>
    </div>
    <i>Demo is reset hourly</i>
</div>

<h1>PrestaShop Demo</h1>
<div class="magentoDemo">
    <div class="magento-frontend">
        <h2>Front-end</h2>
        <a href="http://prestashop.vehiclefits.com/index.php">Demo Front-End</a>
    </div>

    <div class="magento-backend">
        <h2>Admin Panel</h2>
        <a href="http://prestashop.vehiclefits.com/admin2">Demo the Admin</a><br /> Username: josh.ribakoff@gmail.com<br /> Password: admin123


    </div>
</div>