
<div class="row">
    <div class="col-md-6">
        <h1>Magento Demo</h1>
        <a href="http://demo.vehiclefits.com/index.php">Front-End</a><br />
        <a href="http://demo.vehiclefits.com/index.php/admin">Admin</a>
        <br /> Username: admin<br /> Password: admin123
    </div>
    <div class="col-md-6">

        <h1>PrestaShop Demo</h1>
        <a href="http://prestashop.vehiclefits.com/index.php">Front-End</a><br />
        <a href="http://prestashop.vehiclefits.com/vfadmin/public">Admin</a>
        <br /> Username: sales@vehiclefits.com<br /> Password: admin123
    </div>
</div>