<h1>V2</h1>
April 24, 2013 Vehicle-Fits-Magento.v2-build44
(<a href="/downloads/Vehicle-Fits-Magento.v2-build44.tar.gz">tar.gz</a> |
<a href="/downloads/Vehicle-Fits-Magento.v2-build44.zip">zip</a>)

<br />

April 22, 2013 Vehicle-Fits-Magento.v2-build37
(<a href="/downloads/Vehicle-Fits-Magento.v2-build37.tar.gz">tar.gz</a> |
<a href="/downloads/Vehicle-Fits-Magento.v2-build37.zip">zip</a>)

<h1>V1</h1>
Vehicle-Fits-Magento-1.34.zip
(<a href="/downloads/Vehicle-Fits-Magento-1.34.zip">zip</a>)