

<div class="row">
    <div class="col-md-6">
        <h3><i class="icon-cloud-download"></i> Latest Stables</h3>
        <p>These are the latest stable, officially supported releases.</p>

        <h2>3.0.2</h2>
        <ul>
            <li>Released: October 17, 2013</li>

            <li>Download:
                <ul>
                    <li><a href="/downloads/vfmagento-3.0.2.tar.gz">tar.gz</a></li>
                    <li><a href="/downloads/vfmagento-3.0.2.zip">zip</a></li>
                </ul>
            </li>
        </ul>

        <h2>2.0.2</h2>
        <ul>
            <li>Released: October 17, 2013</li>

            <li>Download:
                <ul>
                    <li><a href="/downloads/vfmagento-2.0.2.tar.gz">tar.gz</a></li>
                    <li><a href="/downloads/vfmagento-2.0.2.zip">zip</a></li>
                </ul>
            </li>
        </ul>
    </div>
    <div class="col-md-6">
        <h3><i class="icon-question-sign"></i> Support</h3>
        <p> There is <a href="http://vehiclefits.com/documentation/index">documentation</a>, as well as <a href="http://vehiclefits.com/forums/">Forums</a> for community support.</p>

        <p><a href="<?=$this->url(array('controller'=>'support'),null,true)?>">Paid Support</a> is also available, all proceeds help maintain the software.</p>

        <h3><i class="icon-exclamation-sign"></i> Requirements</h3>
        <p>These versions should work with all known versions of Magento. 3.x requires PHP 5.3 or higher. 2.x requires PHP 5.2 or higher.</p>

        <h3><i class="icon-github-sign"></i> GitHub Source Code</h3>
        <p>Bleeding edge (possibly unstable) versions are available on our <a href="https://github.com/vehiclefits">git hub page</a>. Most users should not venture here, and should instead grab one of the stable releases from this download page. However if you want to help with development of the software, head on over.</p>
    </div>
</div>

<hr />

<h3><i class="icon-archive"></i> Old Versions</h3>
<p>These are unsupported, but made available for historical reasons.</p>

<div class="row">
    <div class="col-md-4">
        <h2>3.0.1</h2>
        <ul>
            <li>Released: October 14, 2013</li>

            <li>Download:
                <ul>
                    <li><a href="/downloads/vfmagento-3.0.1.tar.gz">tar.gz</a></li>
                    <li><a href="/downloads/vfmagento-3.0.1.zip">zip</a></li>
                </ul>
            </li>
        </ul>

        <h2>3.0.0</h2>
        <ul>
            <li>Released: October 13, 2013</li>

            <li>Download:
                <ul>
                    <li><a href="/downloads/vfmagento-3.0.0.tar.gz">tar.gz</a></li>
                    <li><a href="/downloads/vfmagento-3.0.0.zip">zip</a></li>
                </ul>
            </li>
        </ul>
    </div>
    <div class="col-md-4">
        <h2>2.0.1</h2>
        <ul>
            <li>Released: April 24, 2013</li>

            <li>Download:
                <ul>
                    <li><a href="/downloads/Vehicle-Fits-Magento.v2-build44.tar.gz">tar.gz</a></li>
                </ul>
            </li>
        </ul>

        <h2>2.0.0</h2>
        <ul>
            <li>Released: April 22, 2013</li>

            <li>Download:
                <ul>
                    <li><a href="/downloads/Vehicle-Fits-Magento.v2-build37.tar.gz">tar.gz</a></li>
                </ul>
            </li>
        </ul>
    </div>
    <div class="col-md-4">
        <h2>1.34</h2>
        <ul>
            <li>Released: ???</li>

            <li>Download:
                <ul>
                    <li><a href="/downloads/Vehicle-Fits-Magento-1.34.zip">zip</a></li>
                </ul>
            </li>
        </ul>
    </div>
</div>