<a name="back to top"></a>
<b>Product Features</b>
<ul>
    <li><a href="#auto_hide">Does it automatically hide those makes/models/years that do not have product?</a></li>
    <li><a href="#exclude_category">Can it exclude a specific category or products?</a></li>
    <li><a href="#all_category">Can it search all categories at once?</a></li>
	<li><a href="#custom_options">Can I show custom product options based on the vehicle the user has selected?</a></li>
</ul>

<b>Customizing</b>
<ul>
    <li><a href="#change_levels">I want to change what the dropdowns say, for example "Make/Model/Trim", how does that work?</a></li>
    <li><a href="#vertical">Can I choose to show it horizontally vs vertically?</a></li>
	<li><a href="#layered">My customers need to tell me more about their car, like engine size, bed size, door length, seat type, wheel size, how does that work?</a></li>
</ul>	

<b>Data Import &amp; Setup</b>
<ul>
    <li><a href="#one_by_one">So do I have to set up each vehicle and product "one by one"?</a></li>
	<li><a href="#import">How do I import my existing data into this thing?</a></li>
</ul>

<b>Other</b>
<ul>
    <li><a href="#why_need">Why do I need this?</a></li>

</ul>





<br />
<a name="auto_hide"></a>
<b>Does it automatically hide those makes/models/years that do not have product?</b>
<br />
Yes, it will only show make/model/years on the front-end that have product. So if you only have product for 1998/Honda/Civic, it will only show a 1998/Honda/Civic . This greatly reduces the clutter that can quickly kill your sale.
<br /> [<a href="#back to top">back to top</a>]

<br />
<br />

<a name="exclude_category"></a>
<b>Can it exclude a specific category or products?</b>
<br />
Yes, you can set a product as universal so it will always return in all searches. You can hide the filter on any category using Magento's design overrides on a per category level. You can exclude category ids from showing up in the homepage search.
<br />[<a href="#back to top">back to top</a>]

<br />
<br />

<a name="all_category"></a>
<b>Can it search all categories at once?</b>
<br />
Yes, it provides a site search on your homepage, where customers can enter their automobile and it will search all categories. You can choose to have, or not have, a dropdown allowing them to choose between a specific category and all categories. See <a href="http://vehiclefits.com/about/search.php">the category chooser</a>.
<br />[<a href="#back to top">back to top</a>]

<br />
<br />


<a name="custom_options"></a>
<b>Can I show custom product options based on the vehicle the user has selected?</b>
<br />
Yes bundle / kit products in Magento will have their options filtered based on the vehicles assigned to those products. In this way you can have a product or "kit" that is universal or fits many vehicles, and you can have different components in this "kit" that each only fit a handful of vehicles. In this way you might have for example a suspension kit that fits all "Ford", but you might have different options only available on F-150s. Or certain options available based on the trim, engine, or chassis value.
<br />[<a href="#back to top">back to top</a>]

<br />
<br />


<br />
<a name="change_levels"></a>
<b>I want to change what the dropdowns say, for example "Make Model Trim", how does that work?</b>
<br />
You can easily set up what you want your drop-downs to be. You could have just a single dropdown "manufacturer" or "brand", although Magento does that out of the box. Most likely you want to do 2 or more drop-downs, you can add as many drop-downs as you want, and they can be labelled whatever you want, translated, etc...
<br />[<a href="#back to top">back to top</a>]


<br />
<a name="vertical"></a>
<b>Can I choose to show it horizontally vs vertically?</b>
<br />
Yes, you can easily choose wether or not a  &lt;br&gt; tag is output. There are also CSS hooks.
<br />
You can show it horizontally or vertically, in any sidebar, or content area in your Magento site.
<br />[<a href="#back to top">back to top</a>]

<br />
<br />

<a name="layered"></a>
<b>My customers need to tell me more about their car, like engine size, bed size, door length, seat type, wheel size, how does that work?</b>
<br />
The Make Model Year search <a href="http://vehiclefits.com/about/search.php">integrates with layered navigation</a>. Magento's <a href="http://www.magentocommerce.com/product/features/catalog-browsing/view">layered navigation</a> is a multi-faceted filter, allowing your products to be filtered by "attributes", such as color, size, or anything you set up. Your products, lets say wheels, should each have an attribute like size. After the user selects their vehicle the user will be able to enter the size wheel they are looking for.
<br />[<a href="#back to top">back to top</a>]

<br />
<br />



<a name="one_by_one"></a><b>So do I have to set up each vehicle and product "one by one"?</b>
<br />
<p>By no means would that be required, as it would take too much time! We offer a  <a href="http://vehiclefits.com/databases.php">100,000+ record <i>make/model/year</i> &amp; <i>make/model/trim/year</i> database</a>. There are also multiple formats for <a href="http://vehiclefits.com/about/data.php">importing your existing data</a>.</p>

<p>There are features allowing you to import your list of vehicles, as well as for matching your vehicles up to the products. Even if you have to use the control panel and set up your product to vehicle associations manually, you can easily add many vehicles at once. For instance if you know your product "fits all hondas except for a small list of 'exceptions'", you can have your job done in 5 minutes by adding year ranges, or entire "sections" of your make model year hierarchy at once! For instance you could select Make: Honda and then leave Models: All, from there you could "check off" any exceptions and delete them. This is called our <a href="/about/mapping_fits_to_products.php#mass_assign">Mass Assign Feature</a>. </p>
<p>If you are selling wheels and tires you will definitely want to check out our <a href="/modules/wheel.php">Bolt Pattern Fitment Tool</a>!</p>
<br />[<a href="#back to top">back to top</a>]

<br />
<br />

<a name="import"></a><b>How do I import my existing data into this thing?</b>
<br />
That depends, 99% of people in the industry usually format their data in one of several formats, all of which we support. <a href="http://vehiclefits.com/about/data.php">list of the supported formats for importing make model year data</a>; If your format is not listed contact us and we will consider adding it. 
<br />[<a href="#back to top">back to top</a>]

<br />
<br />


<a name="why_need"></a><b>Why do I need this?</b>
<br />
If you are trying to implement "categories within categories", that is, if within each product category you are setting up categories for each vehicle manually, it can save you a lot of time. It can save you a lot of time setting up your categories, and it can save you time matching the products to the vehicles. It provides dropdowns that are ajax powered instead of text-links! It can save you from figuring out each individual vehicle fits each product
<br />[<a href="#back to top">back to top</a>]