<p>
	The vehicle fit extension has been implemented as an enhancement for the <a target="_blank" href="http://magentocommerce.com">Magento e-commerce platform</a>, which has an <a href="http://www.magentocommerce.com/download">open source (free) version available</a>. From the customer's perspective the user picks a make, then the models load in via AJAX!. After subsequently choosing a model the customer can pick the year/options. The Vehicle Fits extension adds features to the front &amp; back-end of this shopping cart. Be sure to check out the <a href="http://vehiclefits.com/faq">FAQ</a> for lighter reading. <strong>Screenshots &amp; videos are in each section below.</strong>
</p>

<div class="tour">

 <div class="tour-item">
     <img src="/photos/search-small.jpg" />
 </div>
 <div class="tour-item">
     <img src="/photos/import-small.jpg" />
     </div>
 <div class="tour-item">
     <img src="/photos/admin-small.jpg" />
     </div>
 <div class="tour-item">
     <img src="/photos/logo_example2-small.jpg" />
     </div>


 <div class="tour-item">
     
    <br />
<strong><a href="/about/search">Search By Vehicle</a></strong>
<p>Customizing & Adding Chained Select Boxes, Vehicle Selection Stays In Session, Hide options that do not have product, Vehicle Applications Listed On Product Page ,   
    Select Box Animation, My Garage / Low Profile Mode, Category Splash Page, Adding a 'Category' Selection To The Search Options, Ajax Mode or Offline Mode, Search on Category Pages (Hide/Show), Site Search From Homepage (Hide/Show),
   Vertical or Horizontal mode, Runs in all modern browsers, Supports Multiple Stores. <a href="/about/search">Read More</a>
</p>
 </div>
        
<div class="tour-item">
	
    <br />
<strong><a href="/about/data">Data Import/Export</a></strong>
<p>At the click of a button, all your complex automotive data is comprehensively loaded into your automotive search engine. Vehicles List Import/Export, Multiple 'Levels' By Comma, Year Ranges, or Not. Or any Numeric Range, Product Application Fitments Import/Export
Product Application Wild Cards, Use your own data or use ours!, Data Insight. <a href="/about/data">Read More</a></p>
</div>

    <div class="tour-item">
    
    <br />
<strong><a href="/about/admin">Administration</a></strong>
<p>Integrates with Magento Product Edit Page, Add vehicles in bulk to a product, ex add all "Hondas" in one click, or add all "Honda Civics" in only one click, Ability to add many vehicle fitments without having to press "save" each time, Duplicate Vehicles When Duplicating A Product, Custom 'levels' and Year Ranges. <a href="/about/admin">Read More</a></p>
</div>

    <div class="tour-item">
    
    <br />
<strong><a href="/about/logos">Car Logos</a></strong>
<p>The LOGO module also displays the logo of the currently selected vehicle next to the search. The benefits of this include.
    * Clear indication of customers selected vehicle
    * Improves aesthetics
    * Helps customer locate vehicle more quickly
    <a href="/about/logos">Read More</a>
</p>
</div>


     <div class="tour-item">
     <img src="/photos/search-results-small.jpg" />
     </div>

     <div class="tour-item">
	 <img src="/feature-icons/notes_small.jpg" />
     </div>

     <div class="tour-item">
     </div>

     <div class="tour-item">
	 <img src="/feature-icons/universal_small.jpg" />
     </div>
    
    
    <div class="tour-item">
<strong><a href="/about/search-results">Search Results</a></strong>
<p>After choosing their vehicle from the homepage, product from all categories can be displayed in a variety of formats (Grid,Category,Grouped). <a href="/about/search-results">Read More</a></p>
    </div>

    
<div class="tour-item">
<strong><a href="/about/fitment_notes">Fitment Notes</a></strong>
<p>The 'compatibility' notes module allows you to add a qualitative criteria to an application fitment. This allows for a free form description of the fitment. (Examples: Vehicle Manufacture Month Mid Year Model Change, Disclaimers). <a href="/about/fitment_notes">Read More</a> </p>
</div>

<div class="tour-item">
<strong><a href="/about/faceted">Faceted (Layered) Navigation</a></strong>
<p>Organize your catalog based on any attribute, for instance if selling pickup truck covers, the customer can search for parts by bed size, color, price, all while filtering by vehicle. <a href="/about/faceted">Read More</a></p>
</div>

<div class="tour-item">
<strong><a href="/about/universal">Universal Products</a></strong>
<p>Ability to have a "universal product" that shows up for all vehicle searches. <a href="/about/universal">Read More</a></p>
</div>

    <div class="tour-item">
    </div>
    <div class="tour-item">
     <img src="/photos/shock-small.jpg" />
     </div>
    <div class="tour-item">
	<img src="/photos/seo-small.jpg" />
    </div>
    <div class="tour-item">
    </div>

<div class="tour-item">
<strong><a href="/about/checkout">Checkout</a></strong>
<p>Verify that the customer purchased a part for the correct application fitment, Require customer to select vehible before checking out. <a href="/about/checkout">Read More</a></p>
</div>

<div class="tour-item">
<strong><a href="/about/bundle">Suspension &amp; Kits</a></strong>
<p>The available parts for a kit should be dependant on the vehicle that is selected. The suspension kit module allows just this. <a href="/about/bundle">Read More</a></p>
</div>

<div class="tour-item">
<strong><a href="/about/seo">Automotive Aftermarket SEO</a></strong>
<p>have landing pages for the people who are searching for specific automotive search queries, example: "Honda Civic 2006 Dash Kit". Google Shopping, Yahoo Sitemap XML, Google Sitemap XML
    HTML Sitemap, Dynamic Autmotive Product Titles, Link Directory. <a href="/about/seo">Read More</a>
 </p>
 </div>

 <div class="tour-item">
<strong><a href="/about/snippets">Design</a></strong>
<p>"My Vehicle" Section On Your Site, PHP Snippet Library   Search Form (Move the Form, Use in a .phtml template, Use in CMS page, Display Horizontally, Style with CSS).
    Search Results (Grouped Products, Category).
 <a href="/about/snippets">Read More</a></p>
</div>


     <div class="tour-item">
     <img src="/photos/paint-small.jpg" />
     </div>

     <div class="tour-item">
	 <img src="/photos/wheel-small.jpg" />
     </div>

     <div class="tour-item">
	    <img src="/photos/wheel-adapter-small.jpg" />
     </div>

     <div class="tour-item">
	 <img src="/photos/tire-small.jpg" />
     </div>

<div class="tour-item">
<strong><a href="/about/paint">Paint Codes</a></strong>
<p>Offer a painting service for paintable products, automatically "knows" the color of your customer's car. <a href="/about/paint">Read more</a></p>
</div>

<div class="tour-item">
<strong><a href="/about/wheel">Wheels</a></strong>
<p>Search By Bolt Pattern, Search By Vehicle (A bolt pattern is a measurement that can be used to determine if the bolts of the wheel match the bolt pattern of the vehicle.. ) <a href="/about/wheel">Read More</a></p>
</div>

<div class="tour-item">
<strong><a href="/about/wheel-adapter">Wheel Adapters</a> - <span style="color:red;">Beta</span></strong>
<p>Search By Wheel Adapter Size(s), Search By Vehicle On Vehicle Side. When you add the vehicle side bolt pattern for an adapter, the corresponding vehicles are derived & automatically added to that product. <a href="/about/wheel-adapter">Read More</a></p>
</div>

<div class="tour-item">
<strong><a href="/about/tire">Tires - <span style="color:red;">Beta</span></a></strong>
<p>The tire package allows your customers to search by tire size, or by vehicle (finds matching vehicles based on tire size automatically). <a href="/about/tire">Read More</a></p>
</div>


</div>