<div id="footer">
    &copy; Vehicle Fits |
    <a href="/documentation/index">Documentation</a> |
    <a href="/faq">FAQ</a> |
    <a href="/ne8_license.rtf">Terms</a> |
    <a href="https://github.com/vehiclefits?tab=members">Contributors</a> |
    <a href="/examplesites">Our Clients</a> |
    <a href="/changelog">Change Log</a> |
    <a href="/demo">Demo</a> |
    <a href="/contact">Contact Us</a>
</div>