<link href="http://crm.vehiclefits.com/themes/Sugar/calendar-win2k-cold-1.css?s=4ceec7985684ec876ebd2ae15a684561&amp;c=1" rel="stylesheet" type="text/css" media="all" mce_href="themes/Sugar/calendar-win2k-cold-1.css?s=4ceec7985684ec876ebd2ae15a684561&amp;c=1">
<script src="http://crm.vehiclefits.com/include/javascript/sugar_grp1.js?s=4ceec7985684ec876ebd2ae15a684561&amp;c=1" type="text/javascript" language="Javascript"></script>
<script src="http://crm.vehiclefits.com/jscalendar/lang/calendar-en.js?s=4ceec7985684ec876ebd2ae15a684561&amp;c=1" type="text/javascript" mce_src="jscalendar/lang/calendar-en.js?s=4ceec7985684ec876ebd2ae15a684561&amp;c=1"></script>
<form action="<?=$_SERVER['PHP_SELF']?>" name="WebToLeadForm" method="POST" id="WebToLeadForm">
    <input type="hidden" name="go" value="<?=htmlentities($url)?>" />
  <table class="mceVisualAid" style="border-top: 1px solid; border-bottom: 1px solid; padding: 10px 6px 12px 10px; background-color: rgb(233, 243, 255); font-size: 12px; background-repeat: repeat-x; background-position: center top;" width="100%">
    <tbody>
      <tr style="color: rgb(0, 105, 225); font-family: Arial,Verdana,Helvetica,sans-serif; font-size: 18px; font-weight: bold; margin-bottom: 0px; margin-top: 0px;" align="center">
        <td class="mceVisualAid" colspan="4"><b>
          <h2>Before we take you there, we'd liked to kindly ask you...</h2>
          </b></td>
      </tr>
      <tr style="color: rgb(0, 105, 225); font-family: Arial,Verdana,Helvetica,sans-serif; font-size: 2px; font-weight: normal; margin-bottom: 0px; margin-top: 0px;" align="center">
        <td class="mceVisualAid" colspan="4">&nbsp;</td>
      </tr>
      <tr style="color: rgb(0, 105, 225); font-family: Arial,Verdana,Helvetica,sans-serif; font-size: 12px; font-weight: normal; margin-bottom: 0px; margin-top: 0px;" align="left">
        <td class="mceVisualAid" colspan="4">Please submit the following information, this will not be shared with any third parties or used for any other purpose then following up regarding Year Make Model searches. </td>
      </tr>
      <tr style="color: rgb(0, 105, 225); font-family: Arial,Verdana,Helvetica,sans-serif; font-size: 8px; font-weight: normal; margin-bottom: 0px; margin-top: 0px;" align="center">
        <td class="mceVisualAid" colspan="4">&nbsp;</td>
      </tr>
      <tr>
        <td class="mceVisualAid" style="text-align: left; font-size: 12px; font-weight: normal;" width="15%"><span sugar="slot">First Name: </span><span class="required" style="color: rgb(255, 0, 0);">*</span></td>
        <td class="mceVisualAid" style="font-size: 12px; font-weight: normal;" width="35%"><span sugar="slot">
          <input id="first_name" name="first_name" type="text">
          </span></td>
        <td class="mceVisualAid" style="text-align: left; font-size: 12px; font-weight: normal;" width="15%"><span sugar="slot">&nbsp;</span></td>
        <td class="mceVisualAid" style="font-size: 12px; font-weight: normal;" width="35%"><span sugar="slot">&nbsp;</span></td>
      </tr>
      <tr>
        <td class="mceVisualAid" style="text-align: left; font-size: 12px; font-weight: normal;" width="15%"><span sugar="slot">Last Name: </span><span class="required" style="color: rgb(255, 0, 0);">*</span></td>
        <td class="mceVisualAid" style="font-size: 12px; font-weight: normal;" width="35%"><span sugar="slot">
          <input id="last_name" name="last_name" type="text">
          </span></td>
        <td class="mceVisualAid" style="text-align: left; font-size: 12px; font-weight: normal;" width="15%"><span sugar="slot">&nbsp;</span></td>
        <td class="mceVisualAid" style="font-size: 12px; font-weight: normal;" width="35%"><span sugar="slot">&nbsp;</span></td>
      </tr>
      <tr>
        <td class="mceVisualAid" style="text-align: left; font-size: 12px; font-weight: normal;" width="15%"><span sugar="slot">Office Phone: </span></td>
        <td class="mceVisualAid" style="font-size: 12px; font-weight: normal;" width="35%"><span sugar="slot">
          <input id="phone_work" name="phone_work" type="text"><br /><input type="checkbox" name="callback" value="yes" /> Please Call Me
          </span></td>
        <td class="mceVisualAid" style="text-align: left; font-size: 12px; font-weight: normal;" width="15%"><span sugar="slot">&nbsp;</span></td>
        <td class="mceVisualAid" style="font-size: 12px; font-weight: normal;" width="35%"><span sugar="slot">&nbsp;</span></td>
      </tr>
      <tr>
        <td class="mceVisualAid" style="text-align: left; font-size: 12px; font-weight: normal;" width="15%"><span sugar="slot">Mobile: </span></td>
        <td class="mceVisualAid" style="font-size: 12px; font-weight: normal;" width="35%"><span sugar="slot">
          <input id="phone_mobile" name="phone_mobile" type="text">
          </span></td>
        <td class="mceVisualAid" style="text-align: left; font-size: 12px; font-weight: normal;" width="15%"><span sugar="slot">&nbsp;</span></td>
        <td class="mceVisualAid" style="font-size: 12px; font-weight: normal;" width="35%"><span sugar="slot">&nbsp;</span></td>
      </tr>
      <tr>
        <td class="mceVisualAid" style="text-align: left; font-size: 12px; font-weight: normal;" width="15%"><span sugar="slot">Email: </span><span class="required" style="color: rgb(255, 0, 0);">*</span></td>
        <td class="mceVisualAid" style="font-size: 12px; font-weight: normal;" width="35%"><span sugar="slot">
          <input id="webtolead_email1" name="webtolead_email1" onChange="validateEmailAdd();" type="text">
          </span></td>
        <td class="mceVisualAid" style="text-align: left; font-size: 12px; font-weight: normal;" width="15%"><span sugar="slot">&nbsp;</span></td>
        <td class="mceVisualAid" style="font-size: 12px; font-weight: normal;" width="35%"><span sugar="slot">&nbsp;</span></td>
      </tr>
      <tr style="color: rgb(0, 105, 225); font-family: Arial,Verdana,Helvetica,sans-serif; font-size: 18px; font-weight: bold; margin-bottom: 0px; margin-top: 0px;" align="center">
        <td class="mceVisualAid" colspan="4">&nbsp;</td>
      </tr>
      <tr align="center">
        <td class="mceVisualAid" colspan="2"><input onClick="submit_form();" class="button" name="Submit" value="Submit" type="button"></td>
        <td class="mceVisualAid" colspan="10"><a href="<?=$url?>?gateway_bypass=1"><strong><span style="font-size:larger">No thanks, take me <br />where I wanted to go!</span></strong></a></td>

      </tr>
      <tr>
        <td class="mceVisualAid" style="display: none;"><input id="campaign_id" name="campaign_id" value="584aaf3d-3c15-4b3c-aa7b-4ad12fa99e3f" type="hidden"></td>
      </tr>
      <tr>
        <td class="mceVisualAid" style="display: none;"><input id="assigned_user_id" name="assigned_user_id" value="1" type="hidden"></td>
      </tr>
      <tr>
        <td class="mceVisualAid" style="display: none;"><input id="req_id" name="req_id" value="last_name;first_name;webtolead_email1;" type="hidden"></td>
      </tr>
    </tbody>
  </table>
</form>
<script type="text/javascript">
 function submit_form(){
     if(typeof(validateCaptchaAndSubmit)!='undefined'){
         validateCaptchaAndSubmit();
     }else{
         check_webtolead_fields();
     }
 }
 function check_webtolead_fields(){
     if(document.getElementById('bool_id') != null){
        var reqs=document.getElementById('bool_id').value;
        bools = reqs.substring(0,reqs.lastIndexOf(';'));
        var bool_fields = new Array();
        var bool_fields = bools.split(';');
        nbr_fields = bool_fields.length;
        for(var i=0;i<nbr_fields;i++){
          if(document.getElementById(bool_fields[i]).value == 'on'){
             document.getElementById(bool_fields[i]).value = 1;
          }
          else{
             document.getElementById(bool_fields[i]).value = 0;
          }
        }
      }
    if(document.getElementById('req_id') != null){
        var reqs=document.getElementById('req_id').value;
        reqs = reqs.substring(0,reqs.lastIndexOf(';'));
        var req_fields = new Array();
        var req_fields = reqs.split(';');
        nbr_fields = req_fields.length;
        var req = true;
        for(var i=0;i<nbr_fields;i++){
          if(document.getElementById(req_fields[i]).value.length <=0 || document.getElementById(req_fields[i]).value==0){
           req = false;
           break;
          }
        }
        if(req){
            document.WebToLeadForm.submit();
            return true;
        }
        else{
          alert('Please provide all the required fields');
          return false;
         }
        return false
   }
   else{
    document.WebToLeadForm.submit();
   }
}
function validateEmailAdd(){
    if(document.getElementById('webtolead_email1').value.length >0) {
        if(document.getElementById('webtolead_email1').value.match(/^\w+(['\.\-\+]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,})+$/) == null){
          alert('Not a valid email address');
        }
    }
    if(document.getElementById('webtolead_email2').value.length >0) {
        if(document.getElementById('webtolead_email2').value.match(/^\w+(['\.\-\+]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,})+$/) == null){
          alert('Not a valid email address');
        }
    }
}
</script>

<!-- Google Website Optimizer Conversion Script -->
<script type="text/javascript">
if(typeof(_gat)!='object')document.write('<sc'+'ript src="http'+
(document.location.protocol=='https:'?'s://ssl':'://www')+
'.google-analytics.com/ga.js"></sc'+'ript>')</script>
<script type="text/javascript">
try {
var gwoTracker=_gat._getTracker("UA-333312-2");
gwoTracker._trackPageview("/1103983498/goal");
}catch(err){}</script>
<!-- End of Google Website Optimizer Conversion Script -->
