<?php
Zend_Layout::getMvcInstance()->setLayout('layout2');
echo $this->partial('carousel.phtml');
?>

<div class="section text-center">

    <div class="container">

        <div class="row">
            <div class="col-lg-12">
                <h2>Filter your parts by Year/Make/Model</h2>
                <p>Add automotive features to your shopping cart (Supports <a href="http://www.magentocommerce.com/">Magento</a> &amp; <a href="http://www.prestashop.com/">PrestaShop</a>). We install either shopping cart for you, as well as install the Vehicle Fits extension itself. Once your shopping cart has the Vehicle Fits extension installed, you will have hundreds of automotive features including a year/make/model search.</p>
                <img src="/img/search1.jpg" />
                <img src="/img/search2.jpg" />
                <img src="/img/search3.jpg" />
                <img src="/img/search4.jpg" />
                <hr>
            </div>
        </div><!-- /.row -->

    </div><!-- /.container -->

</div><!-- /.section-colored -->

<div class="section-colored">

    <div class="container">

        <div class="row">
            <div class="col-lg-4 col-md-4">
                <h3><i class="icon-pencil"></i> Pick Any Dropdowns</h3>
                <p>Easily add, remove & rename dropdowns from the admin panel. Add a new dropdown at any time, like "engine".</p>
            </div>
            <div class="col-lg-4 col-md-4">
                <h3><i class="icon-ok-circle"></i> Sell Auto Parts Online</h3>
                <p>Add a Year/Make/Model Search To Your Shopping Cart.</p>
            </div>
            <div class="col-lg-4 col-md-4">
                <h3><i class="icon-fullscreen"></i> Infinite Scalability</h3>
                <p>Easy to customize look &amp; feel, handles millions of fitments in fractions of a second.</p>
            </div>

        </div><!-- /.row -->

    </div><!-- /.container -->

</div><!-- /.section -->

<div class="section">

    <div class="container">

        <div class="row">
            <div class="col-lg-12 text-center">
                <h2>Featured Work</h2>
                <hr>
            </div>
            <div class="col-lg-4 col-md-4 col-sm-6">
                <img class="img-responsive img-home-portfolio" src="/img/portfolio/justsuspension.jpg">
            </div>
            <div class="col-lg-4 col-md-4 col-sm-6">
                <img class="img-responsive img-home-portfolio" src="/img/portfolio/apx3.jpg">
            </div>
            <div class="col-lg-4 col-md-4 col-sm-6">
                <img class="img-responsive img-home-portfolio" src="/img/portfolio/elite.jpg">
            </div>
            <div class="col-lg-4 col-md-4 col-sm-6">
                <img class="img-responsive img-home-portfolio" src="/img/portfolio/onlyfuel.jpg">
            </div>
            <div class="col-lg-4 col-md-4 col-sm-6">
                <img class="img-responsive img-home-portfolio" src="/img/portfolio/caribbean.jpg">
            </div>
            <div class="col-lg-4 col-md-4 col-sm-6">
                <img class="img-responsive img-home-portfolio" src="/img/portfolio/aip.jpg">
            </div>
        </div><!-- /.row -->

    </div><!-- /.container -->

</div><!-- /.section -->

<div class="section-colored">

    <div class="container">

        <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-6">
                <h2>Manage Your Fitments:</h2>
                <ul>
                    <li>Assign multiple fitments to each product</li>
                    <li>Easily see what fitments are assigned to a given product</li>
                    <li>Lightning fast performance</li>
                </ul>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-6">
                <img class="img-responsive" src="/img/admin.png">
            </div>
        </div><!-- /.row -->

    </div><!-- /.container -->

</div><!-- /.section-colored -->

<div class="section">

    <div class="container">

        <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-6">
                <img class="img-responsive" src="/vf-documentation/images/import_definitions.jpg">
            </div>
            <div class="col-lg-6 col-md-6 col-sm-6">
                <h2>Import Your Fitments:</h2>
                <ul>
                    <li>Add vehicles &amp; assign fitments to products</li>
                    <li>Time saving macros for adding fitments:
                        <ul>
                            <li>Automatic 'Y2K' correction.</li>
                            <li>Multiple ways to add ranges of years.</li>
                            <li>Enumerate SKUs By Comma</li>
                            <li>Enumerate Make/Model/Year(s) By Comma</li>
                            <li>Import Wildcards</li>
                        </ul>
                    </li>

                </ul>
            </div>
        </div><!-- /.row -->

    </div><!-- /.container -->

</div><!-- /.section -->

<div class="section-colored">
<div class="container">

    <div class="row well">
        <div class="col-lg-8 col-md-8">
            <h2>Filter Any Parts!</h2>
            <p>The tool is built for all industries in mind. Add a make/model drop-down to any website, even if you don't sell automotive parts.</p>
            <p><strong>Examples:</strong> Wheels, Tires, Truck Grilles, Truck Bed Covers, Printer Cartridges, Wine, Washer Machine Replacement Parts,
                Sewing Machine Parts,  Any accessory, replacement or performance parts, tractor parts, nail gun nails, etc..</p>
        </div>
        <div class="col-lg-4 col-md-4">
            <a class="btn btn-lg btn-primary pull-right" href="/producttour">See More Features!</a>
        </div>
    </div><!-- /.row -->

</div><!-- /.container -->
</div>