<?= $this->doctype() ?>

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <?= $this->headLink() ?>
    <?= $this->headScript() ?>
    <?= $this->headTitle() ?>
    <style type="text/css">
        @import url( '/skin/style.css' );
    </style>
</head>
<body>
<div align="center">
    <div id="header">
        <div id="logo"><a href="/" ><img src="/images/logo.png" alt="Vehicle Fits Year/Make/Model Search" /></a><br />The Year/Make/Model Company!</div>
        <div id="contact">1-877-CAR-1788</div>
        <div id="contact2"><img src="/images/flag.jpg" /> USA Based Development &amp; Support</div>
        <?= $this->layout()->navigation ?>
    </div>
    <div id="content">
        <?= $this->layout()->content ?>
    </div>
</div>

<?php echo $this->partial('footer.phtml') ?>
<?php echo $this->partial('google-analytics.phtml') ?>

</body>
</html>