Paid support is available.:
<br /><br />
Installation is $175.<br />
Premium support is $200 per month, or $1,900 per year and includes unlimited customization, free installations, free upgrades, and discounts on custom development.
<br />New features are built to quote.
<br />We will scrape data off your competitor or distributor's website, format data, and clean up data. Priced to quote.
<br /><br />
We accept check or money order. Mail to:<br />
 <br />
2373 SW Cooper Ln, Port Saint Lucie, FL 34984 USA
<br /> 

<br />
<br />
Include your Full Name, Return Address, Company Name, Email, Phone Number, and list of which items you are purchasing.
<br />
<br />

<h2>Terms</h2>
By remitting payment you <a href="/ne8_license.rtf">agree to all terms</a>.
<br />
<br />
