<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <!-- You'll want to use a responsive image option so this logo looks good on devices - I recommend using something like retina.js (do a quick Google search for it and you'll find it) -->
            <a class="navbar-brand" href="/"><img src="/img/logo_small_white.png" /></a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse navbar-ex1-collapse">
            <ul class="nav navbar-nav navbar-right">

                <li><a href="<?=$this->url(array('controller'=>'producttour'),null,true)?>">Product Tour</a></li>
                <li><a href="<?=$this->url(array('controller'=>'demo'),null,true)?>">Demo</a></li>

                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Download <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a href="<?=$this->url(array('controller'=>'download', 'action'=>'magento'),null,true)?>">Magento Extension</a></li>
                        <li><a href="<?=$this->url(array('controller'=>'download', 'action'=>'prestashop'),null,true)?>">Prestashop Extension</a></li>
                    </ul>
                </li>

                <li><a href="/documentation/index">Documentation</a></li>
                <li><a href="/forums/">Forums</a></li>
                <li><a href="<?=$this->url(array('controller'=>'contact'),null,true)?>">Contact Us</a></li>
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container -->
</nav>
