<ul id="navigation">
    <li><a href="/">Home</a></li>
    <li><a href="<?=$this->url(array('controller'=>'download'))?>"><strong>Download</strong></a></li>
    <li><a href="https://github.com/vehiclefits">Source Code</a></li>
    <li><a href="<?=$this->url(array('controller'=>'support'),null,true)?>">Support</a></li>
    <li><a href="<?=$this->url(array('controller'=>'producttour'),null,true)?>">Product Tour</a>
    <li><a href="<?=$this->url(array('controller'=>'demo'),null,true)?>">Demo</a></li>
    <li><a href="/vf-documentation/index.htm" target="_blank">Documentation</a></li>
    <li><a href="<?=$this->url(array('controller'=>'contact'),null,true)?>">Contact Us</a></li>
</ul>