<ul id="navigation">
    <li><a href="/">Home</a></li>
    <li><a href="<?=$this->url(array('controller'=>'download'),null,true)?>"><strong>Download</strong></a></li>
    <li><a href="<?=$this->url(array('controller'=>'producttour'),null,true)?>">Product Tour</a>
    <li><a href="<?=$this->url(array('controller'=>'demo'),null,true)?>">Demo</a></li>
    <li><a href="/vf-documentation/index.htm" target="_blank">Documentation</a></li>
    <li><a href="/forums/" target="_blank">Forums</a></li>
    <li><a href="<?=$this->url(array('controller'=>'contact'),null,true)?>">Contact Us</a></li>
</ul>