<strong>Support Cost</strong>
<table>
	<tr>
		<td>Installation</td>
		<td>$175</td>
	</tr>
	<tr>
		<td>Upgrades</td>
		<td>$75</td>
	</tr>

</table>
<br />
<strong>Support Issues Billed Hourly</strong>
<table>
	<tr>
		<td>General Questions</td>
		<td>$0</td>
	</tr>
	<tr>
		<td>Consultation on Software Features</td>
		<td>$50/hr</td>
	</tr>
	<tr>
		<td>Simple Modifications</td>
		<td>$50/hr</td>
	</tr>
	<tr>
		<td>Data Clean Up</td>
		<td>$75/hr</td>
	</tr>
	<tr>
		<td>Other Issues</td>
		<td>Upon Request</td>
	</tr>
</table>

<br />
<br />
NOTE: the issue costs are approximate, as the rate may change during the problem solving.
<br /><br />
While the problem is being solved, the initial ticket price may be changed. For example, if additional investigation is required, the rate will be increased. But if a problem turns out to be a software bug, the points will be all returned. We are ready to reconsider the ticket cost if you think you were charged incorrectly.