<h1>Premium Support</h1>
<ul>
    <li>3-day response time for support tickets</li>
    <li>Phone Support</li>
    <li>Installations &amp; Upgrades</li>
    <li>Solving extension conflicts</li>
    <li>Assistance with configuring settings</li>
</ul>

<h2>Ready to See How VehicleFits Can Help You?</h2>
<p>Want to get the ball rolling and talk specifics? <a href="mailto:sales@vehiclefits.com">Email sales@vehiclefits.com</a> or Call 1-877-CAR-1788</p>