<h2>See what our customers are saying</h2>

<p>
    Awesome!<br />
    Works a treat.<br />
    You really know your stuff.<br />
    I'm loving this module and I know my customers will love it to.<br /><i>Tony O'Neill - www.spare-parts-pro.com </i></p>


<p >
    "I just discovered an unexpected benefit to the module. This is a major coup for us.. Awesome, All the work you've done is great. All of this is going to put us light years ahead of our main competitors"
    <br />
    <i>Brian Lyman - www.justsuspension.com </i>
</p>


 
<p >
    "I'm so glad you had created this previously, before I landed this project. This helps the project immensely. Hope you get a bunch more sales off this extension."
    <br />
    <i>Andrew Miller - Rootform, inc.</i>
</p>

<p>
I am so glad that I found you before I launched this project. While I liked the extension from the get go, it is cool to see you take it further. I hope to land another project in the future that will utilize the extension and give you more business. I plan on trying to talk another auto parts company I work with to redo their store with the Magento framework
</p>
<br />

<p >
"I just played around with the extension, Real nice work Ne8!. I really like it. "
</p>
<Br />