<img src="/images/headers/bundled.jpg" alt="bundled products" />
<h3>Sell Suspension Parts &amp; Kits</h3>
<div align="center"><object width="425" height="344"><param name="movie" value="http://www.youtube.com/v/StqtjKSs7Pw&hl=en&fs=1"></param><param name="allowFullScreen" value="true"></param><param name="allowscriptaccess" value="always"></param><embed src="http://www.youtube.com/v/StqtjKSs7Pw&hl=en&fs=1" type="application/x-shockwave-flash" allowscriptaccess="always" allowfullscreen="true" width="425" height="344"></embed></object></div>

<p>When selling suspension kits online, it is desirable to have just one product (suspension kit) per suspension kit "style". With Magento's configurable products, this can be obtained. However within the automotive industry
it is desirable to have certain parts of that kit fit only certain vehicles. So the available parts for a kit should be dependant on the vehicle that is selected. The suspension kit module allows just this.</p>

<h3>Great for Suspension Kit E-commerce</h3>

<div align="center">
	<i>This kit will be different based on which vehicle the customer needs it for.</i>
    <br />
    <a href="http://vehiclefits.com/images/compare_product.jpg"><img border="0" src="http://vehiclefits.com/images/compare_product.jpg" alt="" style="width:100%" /></a>
</div>
<p>Here for example, two different vehicles are selected, notice how the available options in the suspension kit reflect what is available for that vehicle. The suspension kit itself shows up in searches for many vehicles, but certain options are only available on certain vehicles out of those.</p>

<strong>Related News</strong>
<br />
<a href="http://www.aftermarket-ecommerce.com/?p=19">Ne8 Announces Bundle &amp; Kit Product Support</a> - November 3rd, 2009