<img src="/images/headers/checkout.jpg" alt="vehicle checkout" />
<h3>Sales - Customer Order Vehicle Verification</h3>
<div align="center"><object width="425" height="344"><param name="movie" value="http://www.youtube.com/v/TeARzyJiw8M&hl=en&fs=1"></param><param name="allowFullScreen" value="true"></param><param name="allowscriptaccess" value="always"></param><embed src="http://www.youtube.com/v/TeARzyJiw8M&hl=en&fs=1" type="application/x-shockwave-flash" allowscriptaccess="always" allowfullscreen="true" width="425" height="344"></embed></object></div>
<p>
     The <b>last vehicle</b> the customer had searched on will be saved and displayed on the order view page, allowing whoever fulfills the order to <b>verify that the customer purchased a part for the correct application fitment</b>.
     This affords your company an additional chance to catch and <b>correct erroneous catalog information</b> before the shipment is executed, ultimately reducing incorrect orders.
     <br />
	 <div align="center">
	     <img src="/images/order_view_fit.jpg" />
		 <br />
		 <i>Provide a customer centric experience.</i>
	</div>
</p>

<h3>Require Vehicle Entry</h3>

<p>You have the ability to <i>force</i> the customer to <b>select their vehicle before they can proceed with checkout</b>. If enabled, it will automatically do it for products that have vehicles mapped to them. Upon selecting add to cart, if they do not already have a vehicle selected in their session, but there are vehicles <b>available for the selected product</b>, they will be redirected to the intermediate page.</p>

<div align="center"><object width="480" height="385"><param name="movie" value="http://www.youtube.com/v/1ZNuSVkO5uE?fs=1&amp;hl=en_US"></param><param name="allowFullScreen" value="true"></param><param name="allowscriptaccess" value="always"></param><embed src="http://www.youtube.com/v/1ZNuSVkO5uE?fs=1&amp;hl=en_US" type="application/x-shockwave-flash" allowscriptaccess="always" allowfullscreen="true" width="480" height="385"></embed></object></div>

<p>On the intermediate page the customer is presented with a chained select-box interface exactly like the main vehicle search, but <b>only populated with the vehicles for the selected product</b>. The customer must enter in the vehicle before proceeding with checkout. This ensures the customer has a chance to verify compatability. This feature is completely optional and if enabled will only appear where it makes sense.</p>