<img src="/images/headers/faceted.jpg" alt="faceted search" />
<h3>Faceted Search</h3>
<p class="right">
    The vehicle fit filter integrates with Magento's layered navigation system allowing potential customers to combine criteria to further filter down the results of available product. For example, the user
    could want to see all rims that fit their vehicle that are 22" and also under $4,000. With the extension they filter in this manner, or on similiar criteria.
</p>

<div align="center">
	<object width="425" height="344"><param name="movie" value="http://www.youtube.com/v/gA8DjUgE_GY&hl=en_US&fs=1&"></param><param name="allowFullScreen" value="true"></param><param name="allowscriptaccess" value="always"></param><embed src="http://www.youtube.com/v/gA8DjUgE_GY&hl=en_US&fs=1&" type="application/x-shockwave-flash" allowscriptaccess="always" allowfullscreen="true" width="425" height="344"></embed></object>
</div>

<p>
	With this approach you could organize your catalog based on any attribute, for instance if selling pickup truck covers, the customer can search by bed size. If you are selling seats the customer could search by seat configuration type. Since the extension integrates with the layered navigation, the customer would ONLY see seat types applicable to their vehicle. Or would only see the bed sizes specific to his/her pickup truck. We are confident you can imagine the possibilities.
</p>