<h3>Fitment Compatibility Notes </h3>
<div align="center">
    <a href="http://www.youtube.com/watch?v=WFTQwRmIe3U" target="_blank">
        <img src="/images/play-small.gif" />
        View a demo of Fitment Compatibility Notes
    </a>
</div>

<p>
	The 'compatibility' notes module allows you to add a qualitative criteria to an <a href="http://vehiclefits.com/about/admin.php">application fitment</a>. This allows for a free form description of the fitment. When viewing a given product, depending on what vehicle the user has selected, they will see notes relevant to that vehicle+product (fitment) only.
</p>


<h3>Vehicle Manufacture Month Mid Year Model Change</h3>
<p>Car Manufacturers don't exactly have the aftermarket as their number one priority. Sometimes a simple action on the part of a car manufacturer, like a mid year model change, can throw off your cataloging efforts. The notes module can be used to specify qualitative criteria such as "this part only fits Mercedes manufactured from 'this month' to 'that month'".</p>


<h3>I-Pod&trade; Adapters</h3>
<p>If you sell I-Pods&trade; &amp; I-Pod&trade; adapters for vehicle's audio systems,you may have been supplied a list of vehicles that the adapter allegedly works with. Companies that sell I-Pods&trade; and other radio adapter kits have, over time, collected "notes" about "exceptions" to these fitments. Over time your customers write back to tell you "this adapter did work with my 2002 Chevy Tahoe, but there was an issue using next track/prev track". That customer may demand a refund or partial refund. To avoid the situation in the future you need to effectively communicate this possible compatibility hindrance to the customer. The notes module allows you to do just that!</p>