<p>The LOGO module also displays the logo of the currently selected vehicle next to the search. The benefits of this include.</p>

<ul>
	<li>Clear indication of customers selected vehicle</li>
	<li>Improves aesthetics</li>
	<li>Helps customer locate vehicle more quickly</li>
</ul>

<div align="center">
	<img src="/images/logo_example.jpg" />
	<br />
	<object width="425" height="344"><param name="movie" value="http://www.youtube.com/v/9_8bZPQ4njE&hl=en&fs=1"></param><param name="allowFullScreen" value="true"></param><param name="allowscriptaccess" value="always"></param><embed src="http://www.youtube.com/v/9_8bZPQ4njE&hl=en&fs=1" type="application/x-shockwave-flash" allowscriptaccess="always" allowfullscreen="true" width="425" height="344"></embed></object>
	<img src="/images/logos_small.jpg" />
</div>