<img src="/images/headers/paintcodes.jpg" alt="paint codes software" />

<h3>Paint Codes Module</h3>
<p>Our paint codes module enables store owners selling "paintable" products to better leverage their web store.</p>

<p>For example, if you sold spoilers, you would be able to offer a "painting service" the customer can add-on to the product for an extra fee. The customer would be presented with a list of colors available for their vehicle.</p>

<p>The module of course comes pre-loaded with a comprehensive database that gives your store the intelligence needed to "know" about the color of that customer's vehicle.</p>

<br />

The module is $500 which includes paint code data, and "Starter" edition of the vehicle software. Contact us to purchase.

<br /><br />

<div align="center"><img src="http://vehiclefits.com/documentation-1.3/modules/paint/fig4.jpg" style="width:100%" /></div>