<h3>Customizing &amp; Adding Chained Select Boxes</h3>
<div align="center">
    <a href="http://www.youtube.com/watch?v=CHlfmQYpaC4" target="_blank">
        <img src="/images/play-small.gif" />
        View a demo of Customizing The Levels
    </a>
</div>

<div class="right">
    You may need to filter on something else besides just Make/Model/Year. Maybe you just need Model/Year because you sell for one Make only. Maybe you want more, or less selectboxes. The extension has been used in all industries, aftermarkets, and specialty equipment manufacturer markets. Examples include spare parts for washer machines, sewing machines, and other miscellaneous spare, performance, and accessory parts manufacturers.
</div>

<img src="/photos/searches.jpg" />

<h3>Vehicle Selection Stays In Session</h3>
<div align="center">
    <a href="http://www.youtube.com/watch?v=r4Kc1c4aYYE" target="_blank">
        <img src="/images/play-small.gif" />
        View a demo of Vehicle Staying In Session
    </a>
</div>

<p>The vehicle is stored in the customer's session while browsing your store(s). The vehicle that is selected is clearly displayed at all times. When the customer does a search for a vehicle, their vehicle selection is stored. As they click from page to page, or category to category - the vehicle selection "sticks". The customer can easily change or clear their vehicle selection at any time from any page.</p>


<h3>Hide options that do not have product</h3>
<p>Will hide options that do not have product. Will only show <i>Makes/Models/Years</i> that will yield matched product results. Keeps dropdowns clean and concise which avoids losing or confusing the customers.</p>

<h3>Partial Selection</h3>
<div align="center">
    <a href="http://www.youtube.com/watch?v=KhD_SAi2dzk" target="_blank">
        <img src="/images/play-small.gif" />
        View a demo of Making Partial Selections
    </a>
</div>

<p>The user can make a partial selection. So if they do not know the engine, or trim, they can ask to see all products matching a given make/model. In that case, all engines, or all years (or whatever levels you have setup) will be used for filtering. The labels can be changed to "All Makes", "All Models", "All Years" to make the behavior apparent to the user.</p>

<h3>Vehicle Applications Listed On Product Page</h3>
<div align="center">
    <a href="http://www.youtube.com/watch?v=0SwRWG4O9u0" target="_blank">
        <img src="/images/play-small.gif" />
        View a demo of Applications On Product Page
    </a>
</div>

<p>The vehicle applications you add to your products can be listed out on the product page if you desire. This is useful for Automotive B2B where someone reselling your products just wants to see the automotive applications for a product. It is also useful for your regular customers.</p>

<h3>Select Box Animation</h3>
<p>
	<div align="center">
        <a href="http://www.youtube.com/watch?v=E_8D3afbwzs" target="_blank">
            <img src="/images/play-small.gif" />
            View a demo of Select Box Animation
        </a>
    </div>
    The extension is customizable as to how you want to "animate", or unveil each select box in succession. They select boxes can be:
	<ul>
		<li>Shown</li>
		<li>Hidden</li>
		<li>Disabled (grayed)</li>
	</ul>
</p>

<h3>My Garage / Low Profile Mode</h3>
<p>
	<div align="center">
        <a href="http://www.youtube.com/watch?v=wJZDTPXd8NY" target="_blank">
            <img src="/images/play-small.gif" />
            View a demo of Low Profile Mode
        </a>
    </div>
    After the user makes a selection you can have the search box collapse into a low profile "My Garage" type display. This neatly tucks away the drop downs, allowing the user to change or clear if desired. If the user clicks the 'change' link the drop downs will toggle back into visibility.
</p>

<h3>Category Splash Page</h3>
<div align="center">
    <a href="http://www.youtube.com/watch?v=3hMh6T3NzUQ" target="_blank">
        <img src="/images/play-small.gif" />
        View a demo of Category Splash Page
    </a>
</div>
<p>If a user clicks a category they're going to see a bunch of products that don't "fit". For certain categories you want the user to see products only once they enter their vehicle. This can be turned on and off on a category by category basis, and the template file that the user is shown for the splash page is fully customizable. Once the user enters their vehicle they will be shown the matching products.</p>

<h3>Adding a 'Category' Selection To The Search Options</h3>
<img src="/images/categorychooser.jpg" alt="the category chooser on the make/model/year search" class="left" />
<p>
    You can optionally include a 'category chooser' to allow the user to search parts that fit their vehicle from a specific category. You may choose to have "all" as the first option to search all categories, or you may disable the category chooser which will cause it to search all categories by default.
    You can easily control which categories to display, if at all, and how they are presented to your customer.
</p>


<h3>Ajax Mode or Offline Mode</h3>
<p>
    You can run in either AJAX or OFFLINE mode. The difference is Offline mode will give a smoother experience. AJAX mode will keep your actual page size down.
</p>
<p>Offline mode serializes the hierarchy into a javascript array and includes it into your page. If you have many many options you will want to use AJAX mode. Having the choice gives you the ultimate freedom of customization.</p>


<h3>Search on Category Pages (Hide/Show)</h3>
<p>Choose to show/hide the search filter from specific categories. In this way you may only have a single automotive category. Or maybe you have all automotive categories except a few.</p>

<h3>Site Search From Homepage (Hide/Show)</h3>
<p>Choose wether or not to have a "site vehicle search" on your homepage</p>

<h3>Vertical, Horizontal, Anywhere Where and Way You Want it.</h3>
<p>You can display the automotive search anywhere in your site, the left column, the right column, horizontally, vertically, in your main content(center).</p>
<p>It is a custom Magento block. There is a setting to show it horizontally or vertically and it can be moved anywhere in your template by changing the word "left" to to "right", for example.</p>
    
<h3>Runs in all modern browsers</h3>
<p>Supported in all <a href="http://developer.yahoo.com/yui/articles/gbs/">Modern Browsers as defined by the YUI specification</a>. Fully compatable with MSIE, FF, Chrome, Opera, and all modern browsers. Users the <a href="http://jquery.com">JQuery javascript library</a>.</p>

<h3>Supports Multiple Stores</h3>
<p>Ability to add vehicle search to more than one store and manage from one backend.</p>