<img src="/images/headers/seo.jpg" alt="search engine optimization" />
<h3>Search Engine Optimization</h3>

<p>Search Engine Optimization is important for any e-commerce website, but especially important for automotive ones due to intense competition in the field. Let&#8217;s say you sell Dash Kits for Hondas, and Toyotas, most of your customers probably find you right now by searching for:</p>
 &#8220;Honda Dash Kits&#8221;.
 <p> Well, why not actually have landing pages for the people who are searching for <b>specific automotive search queries</b>, example:</p>
 &#8220;Honda Civic 2006 Dash Kit&#8221;

<h3>Auomotive Landing Pages</h3>

<div align="center">
    <a href="http://www.youtube.com/watch?v=fx1svZ43C1E" target="_blank">
        <img src="/images/play-small.gif" />
        View a demo of Automotive Landing Pages
    </a>

	<ul>
		<li>Google Shopping</li>
		<li>Yahoo Sitemap XML</li>
		<li>Google Sitemap XML</li>
		<li>HTML Sitemap</li>
		<li>Dynamic Autmotive Product Titles</li>
	</ul>
</div>

<p>Each vehicle you sell products for will be displayed on a site map that search engines will begin to crawl. After the engines crawl each one of your highly targetted landing pages, all the products that you have marked as compatible for that vehicle fitment will be listed. Each and every vehicle fitment in your catalog will cause yet another highly targetted automotive landing page to be generated on the fly.<br />
	<div align="center">
        <i>Each product will get a targetted URL for each of it&#8217;s compatable vehicles!</i>
    </div>
</p>

<p>Furthmore, the name of the vehicle the user typed into Google will 'transfer' over automatically to be selected in the automotive shop, so they will automatically see filtered parts matching their vehicle.</p>


<h3>Link Directory</h3>
<div align="center">
    <a href="http://www.youtube.com/watch?v=dKBupesmWII" target="_blank">
        <img src="/images/play-small.gif" />
        View a demo of Link Directory
    </a>
</div>

<p>The vehicle directory enables your users to search using a list of regular links rather than or in addition to the drop down boxes.</p>
