<img src="/images/headers/snippet.jpg" />

<h3>"My Vehicle" Section On Your Site</h3>
<p class="right">
    The vehicle the user is searching for can be displayed anywhere within your site, to provide a clear reference point and provide a more personalized customer experience.
    <br />
    <div align="center">
        <img src="/images/myvehicle.jpg" alt="the personalization features of the vehicle fit extension showing the my current vehicle information" />
        <br />
        <i>Vehicle Indicator / My Garage</i>
    </div>
</p>

<h3>Move the Vehicle Search Form</h3>
<p>The search filter can be moved from the left column to the right column, or any other section ("reference") your Magento template provides.</p>

<h3>Use Vehicle Search Form In .phtml Template</h3>
<p>You can use the search block from within a Magento template, for example page/html/header.phtml to put a search in the header (this is good in "horizontal" mode). </p>

<h3>Use in CMS page</h3>
<p>You can include the vehicle search from within a Magento CMS page</p>

<h3>Display Horizontally</h3>
<p>The design guide also gives tips on designing horizontal vs vertical vehicle searches.</p>

<h3>Style With CSS</h3>
<p>You can easily target specific parts of the search with your CSS to style it.</p>

<h3>PHP Snippet Library</h3>
<i>Full control of your site, down to the pixel</i>
<p>
	The my vehicle feature is currently implemented as an optional snippet you would copy paste into your Magento theme. Other similar snippets are available in the <a href="/documentation/index.htm">documentation</a> under the "optional snippets" section. For instance you could place at the top of your category pages a message that stated "showing all products for your 2002 Honda Civic". Another example is the snippet which allows you to add a "compatabile with" list to each product details page. Be sure to check out the <a href="/documentation/index.htm">Optional Snippets</a> in the documentation to see all that is possible.
</p>