<img src="/images/headers/universal.jpg" />
<h3>Universal Products</h3>

<div align="center">
<object width="480" height="385"><param name="movie" value="http://www.youtube.com/v/wUeJDS6iP2s?fs=1&amp;hl=en_US"></param><param name="allowFullScreen" value="true"></param><param name="allowscriptaccess" value="always"></param><embed src="http://www.youtube.com/v/wUeJDS6iP2s?fs=1&amp;hl=en_US" type="application/x-shockwave-flash" allowscriptaccess="always" allowfullscreen="true" width="480" height="385"></embed></object>
</div>

Ability to have a "universal product" that shows up for all vehicle searches. If a part is marked as 'universal' it shows up wether or not the user has a vehicle selected. It shows up no matter what vehicle is selected. This then makes sense because if the user asks to see parts for their vehicle, we want to show them not only parts specifically for that vehicle, but <i>any part</i> that could work with that vehicle. Obviously something like a bumper sticker, decal, or an air freshner would fit every vehicle on the road.

<h3>Non-Mapped Product</h3>
If a part is not mapped to any vehicles, and not marked universal, it will not show up in any vehicle specific search results.