<img src="/images/headers/bolts.jpg" />

<h3>Bolt Patterns</h3>
<div align="center">
	<img src="/images/screenshots/bolt_importing.jpg" alt="wheel bolt pattern import" />
	<br />
	<i>The bolt pattern adds to your vehicles list, and makes the system aware of every vehicle's bolt pattern. The bolt pattern data is included.</i>
</div>
<p>
     A popular way to map products to vehicles, is via a bolt pattern. A bolt pattern is a measurement that can be used to determine if the bolts of the wheel match the bolt pattern of the vehicle..
</p>


<h3>Search By Bolt Pattern</h3>
<div align="center">
    <a href="http://www.youtube.com/watch?v=_ecH3ivpfA4" target="_blank">
        <img src="/images/play-small.gif" />
        View a demo of Search By Bolt Pattern
    </a>
</div>

<p>The user can enter the lug count &amp; stud spread of their vehicle, or of the wheel they are looking for. This is useful in a number of different scenarios, mainly an "experienced customizer" who is looking for a specific size. In this way someone looking for a wheel of a given size can find what they need quickly & effectively.</p>


<h3>Search By Vehicle</h3>
<div align="center">
    <a href="http://www.youtube.com/watch?v=3mmq2HZMbBs" target="_blank">
        <img src="/images/play-small.gif" />
        View a demo of Search By Vehicle
    </a>
</div>

<p>
      With the bolt pattern assigner, you can almost sit back and let the system run on auto-pilot while it finds <b><i>every</i> combination of wheel and vehicle</b> and automatically sets up your entire store! Then your customers can enter in their vehicle without knowing it's given bolt pattern, and all wheels that have a matching bolt pattern will be shown.
</p>

<p>
	We also have <a href="http://vehiclefits.com/databases.php">databases of vehicle bolt patterns</a>.
</p>