<h3>Search By Wheel Adapter Size(s)</h3>
<div align="center">
    <a href="http://www.youtube.com/watch?v=KoebluGSvjQ" target="_blank">
        <img src="/images/play-small.gif" />
        View a demo of Search By Wheel Adapter Size(s)
    </a>
</div>

<p>Allow your customers to purchase wheel adapters, wheel spacers, &amp; other conversion hubs. The wheel adapter package allows you to setup the vehicle side &amp; wheel side bolt patterns of an adapter product. The users can search based on the adapter specifications</p>

<h3>Search By Vehicle On Vehicle Side</h3>
<p>When you add the vehicle side bolt pattern for an adapter, the corresponding vehicles are derived &amp; automatically added to that product, this allows your customers to search by vehicle on the vehicle side, instead of searching by bolt pattern.</p>